name: Add new issues to project board

on:
  issues:
    types: [opened]

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
#      - name: Add issue to project board
#        uses: actions/add-issues-to-projectboard.yml
#        with:
#          project-url: ${{ secrets.PROJECT_URL }}
#          github-token: ${{ secrets.GH_TOKEN }}

        - name: Check out repository
          uses: actions/checkout@v3

        - name: Add issue to project board
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            issue_number=${{ github.event.issue.number }}
            owner_repo=${{ github.repository }}
            project_id=4
            column_id=Todo
  
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/projects/columns/$column_id/cards \
            -d "{\"content_type\":\"Issue\",\"content_id\":$(curl -s -H \"Authorization: token $GITHUB_TOKEN\" https://api.github.com/repos/$owner_repo/issues/$issue_number | jq .id)}"

